### ISSUE TITLE
App crashes after rebuild from config change

### ISSUE THREAD

**Issue by NervosaX** [fyodorvi/jspm-watch#3]
This happens to me pretty much any time I change jspm.config.js data (whether it be by editing meta data, or resolving dependencies). I'm using jspm 0.17 which may or may not be relevant.

``` javascript
Warning: a promise was created in a handler but was not returned from it
    at expandAndCanonicalizeExpression (/home/adam/Programming/work/ui-v2/node_modules/systemjs-builder/lib/arithmetic.js:254:31)
    at exports.traceExpression (/home/adam/Programming/work/ui-v2/node_modules/systemjs-builder/lib/arithmetic.js:228:16)
    at Builder.trace (/home/adam/Programming/work/ui-v2/node_modules/systemjs-builder/lib/builder.js:390:10)
    at Watcher._updateFilesToWatch (/home/adam/Programming/work/ui-v2/node_modules/jspm-watch/index.js:457:30)
    at /home/adam/Programming/work/ui-v2/node_modules/jspm-watch/index.js:904:26
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at Watcher._bundleApp (/home/adam/Programming/work/ui-v2/node_modules/jspm-watch/index.js:881:86)
    at Watcher._initBuilder (/home/adam/Programming/work/ui-v2/node_modules/jspm-watch/index.js:250:18)
    at Timeout._onTimeout (/home/adam/Programming/work/ui-v2/node_modules/jspm-watch/index.js:652:22)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by NervosaX** [comment]
I haven't seen this issue in other projects I set up using the watcher, so I'm tentative about this one. I'll close it if I don't see this one again. I only saw this in a very very large application, which might make it hard to replicate.
